default: &default
  base_url: 'https://www.urhouse.com.tw/tw/rentals/ajax'
  num_of_result: 6
  filter:
    type: 'residential'
    city: '台北市'
    dist: ["中正區","中山區","北投區","萬華區","大同區","內湖區","松山區","大安區","信義區","士林區","南港區","文山區"]
    # city: '新北市'
    # dist: ["三重區","新店區","樹林區","淡水區","永和區","新莊區","中和區","土城區","板橋區","汐止區"]
    rent:
      min: '30000'
      max: '100000'
    residential:
      total_room:
        min: ""
        max: ""
  sort:
    ordering: 'price'
    direction: 'ASC'
    mode: 'list'
    page: 1

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
